name: Deploy Authenticator Microservice

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy na EC2 via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Build da imagem Docker
        run: |
          docker build -t authenticator_ms .

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push da imagem para Docker Hub
        run: |
          docker tag authenticator_ms ${{ secrets.DOCKER_USERNAME }}/authenticator_ms:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/authenticator_ms:latest

      - name: Deploy na EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/authenticator_ms:latest
            docker stop authenticator_ms || true && docker rm authenticator_ms || true
            docker run -d --name authenticator_ms -p 8082:8080 ${{ secrets.DOCKER_USERNAME }}/authenticator_ms:latest
