name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Login no DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build da imagem Docker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/auth-service:latest .

      - name: Push da imagem para DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/auth-service:latest

      - name: Acessar EC2 e fazer pull e restart
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/auth-service:latest
            docker stop auth || true && docker rm auth || true
            docker run -d --name auth -p 8081:8080 ${{ secrets.DOCKER_USERNAME }}/auth-service:latest
